### ISSUE TITLE
explaining "study_condition" and "disease" fields

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicDataCuration#18]
_From @edoardopasolli on December 7, 2017 19:50_

An external user may have some difficulties in understanding how we defined the "study_condition" and "disease" fields. Should we clarify this aspect better somewhere?

_Copied from original issue: waldronlab/curatedMetagenomicData#118_

**Comment by schifferl** [comment]
_From @lwaldron on December 8, 2017 21:30_

I think the canonical location for variable documentation is in the "Description" column of https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/extdata/template.csv. If you would add this @edoardopasolli (and check the adequacy of the rest of the descriptions), then we'll convert this issue to one for @schifferl to parse this file to create automatic codebooks in the vignette and in the `combined_metadata` help page.

**Comment by lwaldron** [comment]
* `study_condition` is always one word, and is the label for this participant for the purposes of the analysis this study was designed around. In case-control studies, the controls are labeled "control". In studies without a contrast, all participants are labeled "control".  Currently, in non-case-control studies (including exposure-control such as diets or lifestyles, or dose-response studies such as BMI), all participants are labeled as "control". 
* `disease` can be a semicolon-delimited array of diseases associated with the participant, even if they are not under study. Should be "none" if no disease is known for the participant.

TODO @paolinomanghi:

* correct `study_condition` so that it always reflects the condition of study, whether it is case-control, exposure-control, or dose
* annotate the design of each an array of study desighs, consistently with bugsigdb.org:
    + case-control
    + cross-sectional observational, not case-control
    + time series / longitudinal observational
    + laboratory experiment
    + randomized controlled trial
    + prospective cohort

**Comment by lwaldron** [comment]
I think the main action item here is for @QuanWan89 to include a `study design` field in the study table in the new metadata database, with the following values. That can be started in Quan's project management (although I don't have access to that):
- case-control
- cross-sectional observational, not case-control
- time series / longitudinal observational
- laboratory experiment
- randomized controlled trial
- prospective cohort
