### ISSUE TITLE
CosteaPI_2017 disease status, healthy?

### ISSUE THREAD

**Issue by luzhang321** [waldronlab/curatedMetagenomicDataCuration#57]
Hi :) 
Recently I was using the sampleMetadata(curatedMetagenomicData 3.0.1). This metadata is really helping a lot. 
1. Since it is already manually curated, can I directly use the metadata collected for my research?

2. I was confused with this dataset: CosteaPI_2017. 

The paper refers to "Subspecies in the global human gut microbiome". 

In their paper, they report "298 newly generated ones (Table EV1)". I download the tableEV1 and found after filtered PRJEB17632 & German samples. It returns 111 samples. 
However when I extract samples with same criteria in sampleMetadata, it returns 107 samples. 
2.1 I am confused with the different sample numbers.

`CosteaPI_2017 <- filter(sampleMetadata, study_name == "CosteaPI_2017") %>%
  filter(country == "DEU") # 31 individuals, 107 samples  `

`CosteaPI_2017_Stable1 <- readxl::read_xlsx("CosteaPI_2017/msb177589-sup-0003-tableev1.xlsx", sheet = "Sheet1") `
`CosteaPI_2017_Stable1_DEU <- filter(CosteaPI_2017_Stable1, ENA_study_accession == "PRJEB17632") %>%
  filter(., Cohort country == "German") waldronlab/curatedMetagenomicData#111 samples  `

2.2 And in their supplementary table, they didn't write healthy individuals. Why the disease column in sampleMetadata for these samples are "healthy"? Is that because you've other sources for curation?

Thank you! it would be great if some suggestions could be given. 

Best Regards,
Lu

**Comment by lwaldron** [comment]
But curatedMetagenomicData contains software + data, and the `sampleMetadata` object is a part of curatedMetagenomicData, and not the curation repo. Not having an open issue on curatedMetagenomicData has the effect of obscuring an open issue from users of the package, and removes the public check and communication that this fix is actually merged into curatedMetagenomicData, defeating a couple of the main purposes of open issue tracking. Cross-listing in this instance would be acceptable since the change must be made in two repositories, but I can't understand the rationale for not wanting an open issue on curatedMetagenomicData.

**Comment by lwaldron** [comment]
@paolinomanghi it looks like there are two outstanding issues here:
- [ ] Looking at the second one (CA_C10039MS2669SA_t0M15, 61 species), I'm a bit in a doubt: to me (again, personal impression) looks like a typical oral microbiome although is signed as a stool. So, I need some more time to check this.
- [ ] Concerning the problem of Ijaz dataset: I confirm that the one you found is an error. I'll upload the corrected table now, and the package should start applying it a few weeks or so. In the meantime, I suggest you to manually annotate that sample as "child", and I'm very sorry for the inconvenience.
